### ISSUE TITLE
MPI asynchronous communication not working correctly for large number of clients

### ISSUE THREAD

**Issue by chariako** [APPFL/APPFL#192]
On the LCRC Bebop cluster, I requested a node (36 cores) and ran a script containing the following line:

> mpirun --bind-to core --map-by core -np 36 python ./mnist_mpi_async.py --partition class_noiid --loss_fn losses/celoss.py --loss_fn_name CELoss --num_epochs 20

This executes the default number of local SGD steps at each client (100) between communications with the server. I have observed that during the 20 epochs, only the first few clients seem to communicate regularly with the server. Eg., the logs of clients 0-6 look like
>     Round LocalEpoch PerIter[s]  TrainLoss  TrainAccu   TestLoss   TestAccu 
         0          0      33.49     0.0000     0.0000     2.3007     6.5600 
         0          1      78.45     0.7465    74.0958     9.1273    45.4500 
         0          2      82.75     0.1395    96.0217     8.5008    46.9100 
         1          0      35.26     0.0000     0.0000     2.2892    30.2000 
         1          1      82.61     0.6411    79.2948     9.5941    45.8200 
         1          2      83.13     0.1323    96.2929     8.6387    46.8300 
         2          0      34.95     0.0000     0.0000     2.1539    33.8500 
         2          1      83.46     0.3465    91.3653     7.4704    47.1900 
         2          2      83.34     0.0876    97.5136     6.7945    47.4000 
         3          0      35.08     0.0000     0.0000     2.0471    30.6500 
         3          1      83.24     0.2069    94.2134     5.8099    47.1000 
         3          2      83.51     0.0693    97.9656     6.6912    47.2200 
         4          0      35.11     0.0000     0.0000     2.0205    37.2500 
         4          1      84.10     0.1425    95.5696     6.5741    47.6400 
         4          2      83.77     0.0506    98.4629     6.0673    47.9200 

For clients 7-34, the logs look like

>      Round LocalEpoch PerIter[s]  TrainLoss  TrainAccu   TestLoss   TestAccu 
         0          0      34.93     0.0000     0.0000     2.3007     6.5600 
         0          1      73.34     1.2296    52.6544     7.5988    37.8500 
         0          2      74.14     0.2988    90.1408    11.0787    44.8400 
         0          3      74.72     0.1435    95.3413    10.5069    45.4000 

I have confirmed that each MPI process is assigned to a different core in the cluster, and that the server never receives an update from MPI processes with higher ID's. The effect seems to be proportional to the computation load/communication frequency, i.e., when I increase the number of local SGD steps, a larger number of higher ID's successfully update the server.

**Comment by Zilinghan** [comment]
Hi @chariako, from your description, my assumption for the reason is the following:
The computation job that each client is very lightweight, such that they can finish in a very short time. As a result, the receiving queue on the server side is always long. Now, maybe the server retrieves the message in the order of MPI rank, so only the first few clients are retrieved, and higher-rank clients are queued for a long time. 
Could you please help me confirm this by adding a random timeout (e.g., 2 to 5 sec) for each client's training code and see if this helps to have all clients involved. - though this should not be a solution, but just to confirm the root of the isuue.

I will work on to see how to have the server receive messages in a first-come-first-serve order instead of in rank-order.

**Comment by chariako** [comment]
I added a random timeout before the client.update() command in run_mpi_async.py, it does not resolve the issue.

**Comment by kibaekkim** [comment]
https://github.com/APPFL/APPFL/blob/f36dd80cad5cf6e268bd798bfbd3b4db9f9fcaad/src/appfl/comm/mpi/mpi_communicator.py#L119-L125

@Zilinghan These lines are written to store the handler of `irecv` to `recv_queue` in the order of client IDs. I think it should be changed to something like `recv_queue.append(...)`; but we also need to make sure the change does not affect the overall communication protocol.

**Comment by kibaekkim** [comment]
I could reproduce the same/similar behaviors on Bebop and one of the GCE workstations.

**Comment by kibaekkim** [comment]
I confirm that the clients with small client IDs (i.e., smaller MPI ranks) are more frequently updated. This is mainly because `self.recv_queue` stores the handlers of `irecv` in the order of client IDs in the following code:
https://github.com/APPFL/APPFL/blob/f36dd80cad5cf6e268bd798bfbd3b4db9f9fcaad/src/appfl/comm/mpi/mpi_communicator.py#L119-L125

If multiple clients are sent to the server, and their `irecv` handlers available in `self.recv_queue`, the server takes the first available handler (i.e., smaller client IDs) returned from `MPI.Request.waitany(..)`:
https://github.com/APPFL/APPFL/blob/f36dd80cad5cf6e268bd798bfbd3b4db9f9fcaad/src/appfl/comm/mpi/mpi_communicator.py#L150

In the reported experiment, these clients are usually the first few ones (i.e., client IDs 1, 2, 3) because the server calls the `recv_local_model_from_client` function less frequently with validation. That is, the example codes runs such that the server runs the validation every time after calling the `recv_local_model_from_client` function. During the time that the server runs the validation, many or most clients finish their local updates and send their models to the server, which result in that the first few clients are available and selected from `self.recv_queue` repeatedly.

This is a pretty simple fix. I will create a PR shortly.
